version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - monitoring_network

  db:
    build: ./InfraBD
    container_name: postgres_db
    environment:
      POSTGRES_USER: faat
      POSTGRES_PASSWORD: faat
      POSTGRES_DB: northwind
    ports:
      - "3000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring_network

  prometheus:
    build:
      context: ./prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_network

volumes:
  postgres_data:

networks:
  monitoring_network:
    driver: bridge